<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'CmsAddress\Mapping\AddressableInterface'              => __DIR__ . '/src/Mapping/AddressableInterface.php',
    'CmsAddress\Mapping\AddressInterface'                  => __DIR__ . '/src/Mapping/AddressInterface.php',
    'CmsAddress\Mapping\IndividualAddressableInterface'    => __DIR__ . '/src/Mapping/IndividualAddressableInterface.php',
    'CmsAddress\Mapping\IndividualAddressInterface'        => __DIR__ . '/src/Mapping/IndividualAddressInterface.php',
    'CmsAddress\Mapping\LegalAddressableInterface'         => __DIR__ . '/src/Mapping/LegalAddressableInterface.php',
    'CmsAddress\Mapping\LegalAddressInterface'             => __DIR__ . '/src/Mapping/LegalAddressInterface.php',
    'CmsAddress\Mapping\PostalAddressableInterface'        => __DIR__ . '/src/Mapping/PostalAddressableInterface.php',
    'CmsAddress\Mapping\PostalAddressInterface'            => __DIR__ . '/src/Mapping/PostalAddressInterface.php',
    'CmsAddress\Mapping\Traits\IndividualAddressableTrait' => __DIR__ . '/src/Mapping/Traits/IndividualAddressableTrait.php',
    'CmsAddress\Mapping\Traits\LegalAddressableTrait'      => __DIR__ . '/src/Mapping/Traits/LegalAddressableTrait.php',
    'CmsAddress\Mapping\Traits\PostalAddressableTrait'     => __DIR__ . '/src/Mapping/Traits/PostalAddressableTrait.php',
    'CmsAddress\Module'                                    => __DIR__ . '/src/Module.php',
    'CmsAddress\Mvc\Controller\AdminController'            => __DIR__ . '/src/Mvc/Controller/AdminController.php',
    'CmsAddress\View\Helper\Address'                       => __DIR__ . '/src/View/Helper/Address.php',
    'CmsAddressTest\Framework\TestCase'                    => __DIR__ . '/tests/Framework/TestCase.php',
    'CmsAddressTest\SampleTest'                            => __DIR__ . '/tests/SampleTest.php',
);
