<?php 
/**
 * CoolMS2 Address Module (http://www.coolms.com/)
 *
 * @link      http://github.com/coolms/address for the canonical source repository
 * @copyright Copyright (c) 2006-2015 Altgraphic, ALC (http://www.altgraphic.com)
 * @license   http://www.coolms.com/license/new-bsd New BSD License
 * @author    Dmitry Popov <d.popov@altgraphic.com>
 */

namespace CmsAddress;

$this->fieldset->get('houseNumber')->setOption('twbs', [
        'col' => ['class' => 'col-xs-12 col-sm-4'],
        'housing' => [
            'type' => 'formGroupElement',
            'content' => 'housing',
            'order' => 9050,
            'placement' => 'append',
        ],
        'apartmentNumber' => [
            'type' => 'formGroupElement',
            'content' => 'apartmentNumber',
            'order' => 9050,
            'placement' => 'append',
        ],
    ]);
$this->fieldset->get('housing')->setOption('twbs', [
        'col' => ['class' => 'col-xs-12 col-sm-4'],
    ]);
$this->fieldset->get('apartmentNumber')->setOption('twbs', [
        'col' => ['class' => 'col-xs-12 col-sm-4'],
    ]);
?>
<?= $this->formCollection($this->fieldset, true, false);
