<?php 
/**
 * CoolMS2 Address module (http://www.coolms.com/)
 * 
 * @link      http://github.com/coolms/CmsAddress for the canonical source repository
 * @copyright Copyright (c) 2006-2015 Altgraphic, ALC (http://www.altgraphic.com)
 * @license   http://www.coolms.com/license/new-bsd New BSD License
 * @author    Dmitry Popov <d.popov@altgraphic.com>
 */

namespace CmsAddress;

$this->fieldset->get('houseNumber')->setOptions([
        'twb' => [
            'decorators' => [
                'col' => ['class' => 'col-xs-12 col-sm-6'],
                'formGroup' => ['elements' => 'housing'],
            ],
        ],
    ]);

$this->fieldset->get('housing')->setOptions([
        'twb' => [
            'decorators' => [
                'col' => ['class' => 'col-xs-12 col-sm-6'],
            ],
        ],
    ]);
